Repository EXA-UQ/EXAUQ-Toolbox, pull requests merged in 2024-12, with the labels that each got.

#368 [ReadyforReview]Update Repository information Post-Release
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  SUPPORT.md
Labels: Bug, Good first issue

#372 [ReadyforReview]iss352 create GitHub pages mkdocs workflow
  .github/workflows/documentation_upload.yml
Labels: Documentation, CI / Automation

#375 Merge dev into main for v0.1.1
  .github/workflows/documentation_upload.yml
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  SUPPORT.md
Labels: Documentation, CI / Automation

#282 [Ready to Review] Implement Multi-Interface Initialisation and Management in CLI
  docs/cli/first-walkthrough.md
  exauq/app/app.py
  exauq/app/cli.py
  exauq/app/startup.py
  exauq/docs/404.html
  exauq/docs/api/SUMMARY.html
  exauq/docs/api/__init__.html
  exauq/docs/api/core/__init__.html
  exauq/docs/api/core/designers.html
  exauq/docs/api/core/emulators.html
  exauq/docs/api/core/modelling.html
  exauq/docs/api/core/numerics.html
  exauq/docs/api/sim_management/__init__.html
  exauq/docs/api/sim_management/hardware.html
  exauq/docs/api/sim_management/jobs.html
  exauq/docs/api/sim_management/simulators.html
  exauq/docs/api/sim_management/types.html
  exauq/docs/cli/first-walkthrough.html
  exauq/docs/cli/index.html
  exauq/docs/cli/user-guides/cancelling-jobs.html
  exauq/docs/cli/user-guides/index.html
  exauq/docs/cli/user-guides/resubmitting-jobs.html
  exauq/docs/cli/user-guides/showing-jobs.html
  exauq/docs/cli/user-guides/simulator-script.html
  exauq/docs/designers/index.html
  exauq/docs/designers/tutorials/index.html
  exauq/docs/designers/tutorials/mlas_tutorial.html
  exauq/docs/designers/tutorials/slas_tutorial.html
  exauq/docs/designers/tutorials/training_gp_tutorial.html
  exauq/docs/designers/tutorials/training_multi_level_gp_tutorial.html
  exauq/docs/index.html
  exauq/docs/objects.inv
  exauq/docs/sitemap.xml.gz
  exauq/sim_management/hardware.py
  exauq/sim_management/simulators.py
Labels: Documentation, Enhancement

#378 [ReadyforReview]Iss377 update pyprojecttoml to pull down latest version
  pyproject.toml
Labels: Info, Good first issue

#361 [ReadyforReview]Update test-package.yml to run poetry lock --no-update
  .github/workflows/test-package.yml
Labels: Bug, CI / Automation

#379 [ReadyforReview]Add -v / --version argument to exauq main
  exauq/__main__.py
Labels: Documentation, Good first issue

#360 [ReadyforReview]Fix empty input in TrainingDatum and add test
  exauq/core/modelling.py
  tests/unit/test_modelling.py
Labels: Bug, Good first issue

#362 [ReadyforReview]Iss287 add seq from array class method to input
  exauq/core/modelling.py
  tests/unit/test_modelling.py
Labels: Enhancement, Good first issue
