Repository EXA-UQ/EXAUQ-Toolbox, pull requests merged in 2025-03, with the labels that each got.

#342 [ReadyforReview]iss332 multi level gp output level wise predictions
  docs/designers/tutorials/mlas_tutorial.md
  docs/designers/tutorials/notebooks/training_multi_level_gp_tutorial.ipynb
  docs/designers/tutorials/slas_tutorial.md
  docs/designers/tutorials/training_gp_tutorial.md
  docs/designers/tutorials/training_multi_level_gp_tutorial.md
  exauq/core/modelling.py
  exauq/docs/api/core/modelling.html
  exauq/docs/designers/tutorials/mlas_tutorial.html
  exauq/docs/designers/tutorials/slas_tutorial.html
  exauq/docs/designers/tutorials/training_gp_tutorial.html
  exauq/docs/designers/tutorials/training_multi_level_gp_tutorial.html
  exauq/docs/sitemap.xml.gz
  tests/unit/test_modelling.py
Labels: Enhancement, Good first issue

#295 [ReadyforReview] Issue 255: prepare for sequential design
  docs/index.md
  exauq/core/designers.py
  exauq/sim_management/simulators.py
  tests/unit/test_designers.py
  tests/unit/test_simulators.py
Labels: Enhancement

#405 [Ready to Review] Rename LICENSE.txt → LICENSE and clean up licensing files
  LICENSE
  LICENSE.txt
  NOTICE
  SUPPORT.md
Labels: Documentation

#404 [ReadyForReview]Iss330 multi level gp not outputting expected errors
  exauq/core/emulators.py
  tests/unit/test_emulators.py
Labels: Bug

#410 [RtR] Add shields/badges, citation section and `CITATION.cff` to improve `README` and citation metadata
  CITATION.cff
  README.md
Labels: Documentation
